# Generated by Django 4.0.1 on 2022-01-24 11:48

import content_pr.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, null=True, upload_to=content_pr.utils.image_path_generator, verbose_name='product images')),
                ('payment_status', models.CharField(choices=[('رایگان', 'رایگان'), ('پولی', 'پولی')], default='رایگان', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='content.Category')),
            ],
        ),
    ]
